
- hosts: storage,quorum,monitor
  become: true
  pre_tasks:
   - setup:
      gather_subset:
        - '!all'
        - '!any'
        - 'network'
  tasks:
  - name: create install_monitor_agent.sh file
    template:
      src: _install_monitor_agent.sh.j2
      dest: /home/opc/install_monitor_agent.sh
    when: install_monitor_agent|bool
  - name: execute install_monitor_agent.sh
    command: bash -c "chmod +x /home/opc/*.sh ; sudo /home/opc/install_monitor_agent.sh"
    when: install_monitor_agent|bool


- hosts: monitor
  become: true
  pre_tasks:
   - setup:
      gather_subset:
        - '!all'
        - '!any'
        - 'network'
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
  - name: stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no
    async: 30
    poll: 0
  - name: create install_monitor_config.sh file
    template:
      src: _install_monitor_config.sh.j2
      dest: /home/opc/install_monitor_config.sh
  - name: execute install_monitor_config.sh
    command: bash -c "chmod +x /home/opc/*.sh ; sudo /home/opc/install_monitor_config.sh"


- hosts: monitor
  become: true
  vars:
    monitoring: true
  tasks:
    - include_role:
        name: prometheus
      when: install_monitor_agent|default(false)|bool
    - include_role:
        name: grafana
      when: install_monitor_agent|default(false)|bool
