variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "authorized_ips" {}
variable "ssh_public_key_file_ol7" {}
variable "ssh_private_key_file_ol7" {}
variable "instance_shape" {}
variable "AD" {}
variable "cidr_vcn" {}
variable "cidr_subnet1" {}
variable "cidr_subnet2" {}
variable "BootStrapFile_ol7" {}
