variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "authorized_ips" {}
variable "ssh_public_key_file_ansible" {}
variable "ssh_private_key_file_ansible" {}
variable "ssh_public_key_file_host1" {}
variable "ssh_private_key_file_host1" {}
variable "AD" {}
variable "cidr_vcn" {}
variable "cidr_subnet1" {}
variable "BootStrapFile_ansible" {}
variable "host1_hostname" {}
