variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "ssh_public_key_file_ol7_desktop" {}
variable "ssh_private_key_file_ol7_desktop" {}
variable "ssh_public_key_file_sgd" {}
variable "ssh_private_key_file_sgd" {}
variable "authorized_ips" {}
variable "sgd_image_ocid" {}
variable "AD" {}
variable "cidr_vcn" {}
variable "cidr_subnet_public" {}
variable "cidr_subnet_private" {}
variable "BootStrapFile_ol7_desktop" {}
variable "BootStrapFile_sgd" {}
