variable "tenant1_tenancy_ocid" {}
variable "tenant1_user_ocid" {}
variable "tenant1_fingerprint" {}
variable "tenant1_private_key_path" {}
variable "tenant1_compartment_ocid" {}
variable "tenant1_region" {}
variable "tenant1_authorized_ips" {}
variable "tenant1_ssh_public_key_file_ol7" {}
variable "tenant1_ssh_private_key_file_ol7" {}
variable "tenant2_tenancy_ocid" {}
variable "tenant2_user_ocid" {}
variable "tenant2_fingerprint" {}
variable "tenant2_private_key_path" {}
variable "tenant2_compartment_ocid" {}
variable "tenant2_region" {}
variable "tenant2_authorized_ips" {}
variable "tenant2_ssh_public_key_file_ol7" {}
variable "tenant2_ssh_private_key_file_ol7" {}
variable "tenant1_AD" {}
variable "tenant1_cidr_vcn" {}
variable "tenant1_cidr_subnet_test" {}
variable "tenant1_BootStrapFile_test" {}
variable "tenant2_AD" {}
variable "tenant2_cidr_vcn" {}
variable "tenant2_cidr_subnet_libreswan" {}
variable "tenant2_cidr_subnet_test" {}
variable "tenant2_libreswan_private_ip" {}
variable "tenant2_BootStrapFile_test" {}
variable "tenant2_BootStrapFile_libreswan" {}
