variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "authorized_ips" {}
variable "AD" {}
variable "cidr_vcn" {}
variable "cidr_subnet1" {}
variable "BootStrapFile_win2016" {}
variable "WinRMFile_win2016" {}
variable "winrm_https_port" {}
