variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "compartment_ocid" {}
variable "authorized_ips" {}
variable "ssh_public_key_file" {}
variable "ssh_private_key_file" {}
variable "dns_label_vcn" {}
variable "dns_label_public" {}
variable "dns_label_private" {}
variable "cidr_vcn" {}
variable "cidr_subnet_public" {}
variable "cidr_subnet_private" {}
variable "AD" {}
variable "cloudinit_script_dbclient" {}
variable "mysql_display_name" {}
variable "mysql_description" {}
variable "mysql_username" {}
variable "mysql_shape_name" {}
variable "mysql_storage_size_in_gb" {}
variable "mysql_hostname" {}
variable "mysql_backup_policy_is_enabled" {}
variable "mysql_backup_policy_retention_in_days" {}
