variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "ssh_public_key_file_ol7" {}
variable "ssh_private_key_file_ol7" {}
variable "authorized_ips" {}
variable "AD" {}
variable "cidr_vcn" {}
variable "cidr_subnet1" {}
variable "number_of_instances" {}
variable "instances_name" {}
variable "instances_hostname" {}
variable "instances_shape" {}
variable "instances_post_prov" {}
