variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "user_name" {}
variable "auth_token" {}
variable "ssh_public_key_file_bastion" {}
variable "ssh_private_key_file_bastion" {}
variable "ssh_public_key_file_dbclient" {}
variable "ssh_private_key_file_dbclient" {}
variable "authorized_ips" {}
variable "adb_type" {}
variable "adb_is_free_tier" {}
variable "adb_cpu_core_count" {}
variable "adb_data_storage_tbs" {}
variable "adb_db_name" {}
variable "adb_password" {}
variable "adb_display_name" {}
variable "adb_license_model" {}
variable "adb_autoscaling_enabled" {}
variable "adb_data_safe_status" {}
variable "adb_wallet_password" {}
variable "adb_wallet_type" {}
variable "adb_wallet_filename" {}
variable "AD" {}
variable "cidr_vcn" {}
variable "cidr_subnet_public" {}
variable "cidr_subnet_private" {}
variable "pub_ip_data_safe_fra" {}
variable "BootStrapFile_dbclient" {}
variable "BootStrapFile_bastion" {}
