# ---- use variables defined in terraform.tfvars file
variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "AD1" {}
variable "AD2" {}
variable "ScriptFile_db" {}
variable "ssh_public_key_file" {}
variable "ssh_private_key_file" {}
variable "authorized_ips" {}
variable "dns_vcn" {}
variable "dns_subnet1" {}
variable "cidr_vcn" {}
variable "cidr_subnet1" {}

variable "BM1-DBNodeShape" {}
variable "BM1-CPUCoreCount" {}
variable "BM1-DBEdition" {}
variable "BM1-DBAdminPassword" {}
variable "BM1-DBName" {}
variable "BM1-DBVersion" {}
variable "BM1-DBDisplayName" {}
variable "BM1-DBDiskRedundancy" {}
variable "BM1-DBNodeDisplayName" {}
variable "BM1-DBNodeHostName" {}
variable "BM1-NCharacterSet" {}
variable "BM1-CharacterSet" {}
variable "BM1-DBWorkload" {}
variable "BM1-PDBName" {}
variable "BM1-LicenseModel" {}
variable "BM1-NodeCount" {}

variable "BM2-DBNodeShape" {}
variable "BM2-CPUCoreCount" {}
variable "BM2-DBEdition" {}
variable "BM2-DBAdminPassword" {}
variable "BM2-DBName" {}
variable "BM2-DBVersion" {}
variable "BM2-DBDisplayName" {}
variable "BM2-DBDiskRedundancy" {}
variable "BM2-DBNodeDisplayName" {}
variable "BM2-DBNodeHostName" {}
variable "BM2-NCharacterSet" {}
variable "BM2-CharacterSet" {}
variable "BM2-DBWorkload" {}
variable "BM2-PDBName" {}
variable "BM2-LicenseModel" {}
variable "BM2-NodeCount" {}

# ---- provider
provider "oci" {
  region           = var.region
  tenancy_ocid     = var.tenancy_ocid
  user_ocid        = var.user_ocid
  fingerprint      = var.fingerprint
  private_key_path = var.private_key_path
}
