variable "g_tenancy_ocid" {}
variable "g_user_ocid" {}
variable "g_fingerprint" {}
variable "g_private_key_path" {}
variable "g_region" {}
variable "g_compartment_ocid" {}
variable "g_ssh_public_key_file" {}
variable "g_ssh_private_key_file" {}
variable "g_authorized_ips" {}
