variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "cidr_vcn" {}
variable "nb_subnets" {}
variable "subnets_cidr" {}
variable "subnets_name" {}
variable "subnets_dnslabel" {}
