variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "region" {}
variable "infra_compartment_id" {}
variable "vmcluster_compartment_id" {}
variable "exacc_infra_id" {}
variable "exacc_vmcluster_network_id" {}
variable "exacc_vmcluster_ocpus" {}
variable "exacc_vmcluster_memory_gbs" {}
variable "exacc_vmcluster_local_storage_gbs" {}
variable "exacc_vmcluster_exa_storage_tbs" {}
variable "exacc_vmcluster_name" {}
variable "exacc_vmcluster_db_server1" {}
variable "exacc_vmcluster_db_server2" {}
variable "exacc_vmcluster_db_server3" {}
variable "exacc_vmcluster_db_server4" {}
variable "exacc_vmcluster_gi_version" {}
variable "exacc_vmcluster_lic_model" {}
variable "exacc_vmcluster_ssh_public_key_file" {}
variable "dbhome1_version" {}
variable "dbhome1_display_name" {}
variable "db_name" {}
variable "db_pdb_name" {}
variable "db_workload" {}
variable "db_character_set" {}
variable "db_ncharacter_set" {}
variable "db_admin_password" {}
variable "dbhome2_db1_name" {}
variable "dbhome2_db1_pdb2_name" {}
variable "dbhome3_version" {}
variable "dbhome3_display_name" {}
