variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "cidr_vcn" {}
variable "cidr_subnet1" {}
variable "authorized_ips" {}
variable "AD" {}
variable "shape" {}
variable "ssh_public_key_file_rdesktop" {}
variable "ssh_private_key_file_rdesktop" {}
variable "BootStrapFile_rdesktop_ol7" {}
variable "BootStrapFile_rdesktop_ubuntu18" {}
variable "is_os_ubuntu" {}