variable "tenancy_ocid" {}
variable "user_ocid" {}
variable "fingerprint" {}
variable "private_key_path" {}
variable "compartment_ocid" {}
variable "region" {}
variable "ssh_public_key_file_ol7" {}
variable "ssh_private_key_file_ol7" {}
variable "authorized_ips" {}
variable "AD" {}
variable "cidr_vcn" {}
variable "cidr_subnet1" {}
variable "BootStrapFile_ol7" {}
variable "BootStrapFile_win2016" {}
variable "rdp_file_win2016" {}
variable "fs1_export_path" {}
variable "fs1_mount_point" {}
variable "win2016_nfs_drive" {}
